RedisExchangeAPI/Models/ErrorViewModel.cs
namespace RedisExchangeAPI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RedisExchangeAPI/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPI.Services;
using StackExchange.Redis;

namespace RedisExchangeAPI.Controllers
{
    public class BaseController : Controller
    {
        protected readonly RedisService _redisService;
        protected readonly IDatabase db;

        public BaseController(RedisService redisService)
        {
            _redisService = redisService;
            db = _redisService.GetDatabase(0);
        }
    }
}

RedisExchangeAPI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPI.Models;
using System.Diagnostics;

namespace RedisExchangeAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RedisExchangeAPI/Controllers/RedisController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeAPI.Services;
using StackExchange.Redis;

namespace RedisExchangeAPI.Controllers
{
    public class RedisController : BaseController
    {
        private readonly string listkey = "listname";
        public string hashKey { get; set; } = "dictionary";
        public RedisController(RedisService redisService):base(redisService)
        {
        }

        public IActionResult Index()
        {
            db.StringSet("rediServiceName","Mehmet Dokuyucu");
            db.StringSet("guest", 100);
            return View();
        }
        public IActionResult Show()
        {
            var servicenameValue = db.StringGet("rediServiceName");
            if (servicenameValue.HasValue)
                ViewBag.value = servicenameValue.ToString();
            return View();
        }
        public IActionResult ListTypeIndex()
        {
            List<string> nameList = new List<string>();
            if (db.KeyExists(listkey))
            {
                db.ListRange(listkey).ToList().ForEach(x =>
                {
                    nameList.Add(x.ToString());
                });
            }
            return View(nameList);
        }
        public IActionResult ListTypeAdd(string name)
        {
            db.ListLeftPush(listkey, name); //listenin başına veri ekleme listrightpush en sona ekler.
            return RedirectToAction("ListTypeIndex");
        }
        public async Task<IActionResult> DeleteListType(string name)
        {
            await db.ListRemoveAsync(listkey,name);
            return RedirectToAction("ListTypeIndex");
        }
        public IActionResult HashTypeIndex()
        {
            Dictionary<string,string> list = new Dictionary<string,string>();

            if (db.KeyExists(hashKey))
            {
                db.HashGetAll(hashKey).ToList().ForEach(x =>
                {
                    list.Add(x.Name, x.Value);
                });
            }

            return View(list);
        }
        public IActionResult HashTypeAdd(string key, string value)
        {
            db.HashSet(hashKey,key,value);
            return RedirectToAction("HashTypeIndex");
        }

        public async Task<IActionResult> DeleteHashType(string name)
        {
            await db.HashDeleteAsync(hashKey, name);
            return RedirectToAction("HashTypeIndex");
        }
    }
}

RedisExchangeAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RedisExchangeAPI/Views/Redis/HashTypeAdd.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

RedisExchangeAPI/Views/Redis/HashTypeIndex.cshtml
@model Dictionary<string, string>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post" asp-action="HashTypeAdd" enctype="application/x-www-form-urlencoded">
    <input type="text" name="key" />
    <input type="text" name="value" />
    <button type="submit">Kaydet</button>

</form>

@foreach (var item in Model)
{
    <h2>@item.Key -> @item.Value  <a asp-controller="Redis" asp-action="DeleteHashType" asp-route-name="@item.Key">Sil</a> </h2>

}

RedisExchangeAPI/Views/Redis/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Index</h1>

RedisExchangeAPI/Views/Redis/ListTypeIndex.cshtml
@model List<string>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post" asp-action="ListTypeAdd" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name"/>
    <button type="submit">Kaydet</button>

</form>

@foreach (var item in Model)
{
    <h2>@item <a asp-controller="Redis" asp-action="DeleteListType" asp-route-name="@item">Sil</a> </h2>
    
}

RedisExchangeAPI/Views/Redis/Show.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>@ViewBag.value</h2>

RedisExchangeAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RedisExchangeAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RedisExchangeAPI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RedisExchangeAPI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RedisExchangeAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>